
CREATE TABLE bronze_gamma_markets (
    id VARCHAR NOT NULL, 
    question VARCHAR NOT NULL, 
    condition_id VARCHAR NOT NULL, 
    slug VARCHAR NOT NULL, 
    resolution_source VARCHAR, 
    end_date VARCHAR, 
    liquidity VARCHAR, 
    start_date VARCHAR, 
    image VARCHAR, 
    icon VARCHAR, 
    description VARCHAR, 
    outcomes VARCHAR, 
    outcome_prices VARCHAR, 
    active BOOLEAN, 
    closed BOOLEAN, 
    market_maker_address VARCHAR, 
    created_at VARCHAR, 
    updated_at VARCHAR, 
    "new" BOOLEAN, 
    featured BOOLEAN, 
    submitted_by VARCHAR, 
    archived BOOLEAN, 
    resolved_by VARCHAR, 
    restricted BOOLEAN, 
    group_item_title VARCHAR, 
    question_id VARCHAR, 
    enable_order_book BOOLEAN, 
    order_price_min_tick_size FLOAT, 
    order_min_size BIGINT, 
    liquidity_num FLOAT, 
    end_date_iso VARCHAR, 
    start_date_iso VARCHAR, 
    has_reviewed_dates BOOLEAN, 
    game_start_time VARCHAR, 
    seconds_delay BIGINT, 
    clob_token_ids VARCHAR, 
    uma_bond VARCHAR, 
    uma_reward VARCHAR, 
    liquidity_clob FLOAT, 
    custom_liveness BIGINT, 
    accepting_orders BOOLEAN, 
    neg_risk BOOLEAN, 
    neg_risk_request_id VARCHAR, 
    ready BOOLEAN, 
    funded BOOLEAN, 
    accepting_orders_timestamp VARCHAR, 
    cyom BOOLEAN, 
    competitive FLOAT, 
    pager_duty_notification_enabled BOOLEAN, 
    approved BOOLEAN, 
    rewards_min_size BIGINT, 
    rewards_max_spread FLOAT, 
    spread FLOAT, 
    best_bid FLOAT, 
    best_ask FLOAT, 
    automatically_active BOOLEAN, 
    clear_book_on_start BOOLEAN, 
    manual_activation BOOLEAN, 
    neg_risk_other BOOLEAN, 
    game_id VARCHAR, 
    sports_market_type VARCHAR, 
    uma_resolution_statuses VARCHAR, 
    pending_deployment BOOLEAN, 
    deploying BOOLEAN, 
    deploying_timestamp VARCHAR, 
    rfq_enabled BOOLEAN, 
    event_start_time VARCHAR, 
    holding_rewards_enabled BOOLEAN, 
    fees_enabled BOOLEAN, 
    requires_translation BOOLEAN, 
    fee_type VARCHAR, 
    line FLOAT, 
    group_item_threshold VARCHAR, 
    maker_base_fee BIGINT, 
    taker_base_fee BIGINT, 
    show_gmp_series BOOLEAN, 
    show_gmp_outcome BOOLEAN, 
    maker_rebates_fee_share_bps BIGINT, 
    volume VARCHAR, 
    volume_num FLOAT, 
    volume_clob FLOAT, 
    last_trade_price FLOAT, 
    volume_24_hr BIGINT, 
    volume_1_wk BIGINT, 
    volume_1_mo BIGINT, 
    volume_1_yr BIGINT, 
    volume_24_hr_amm BIGINT, 
    volume_1_wk_amm BIGINT, 
    volume_1_mo_amm BIGINT, 
    volume_1_yr_amm BIGINT, 
    volume_24_hr_clob BIGINT, 
    volume_1_wk_clob BIGINT, 
    volume_1_mo_clob BIGINT, 
    volume_1_yr_clob BIGINT, 
    volume_amm BIGINT, 
    liquidity_amm BIGINT, 
    one_day_price_change BIGINT, 
    one_hour_price_change BIGINT, 
    one_week_price_change BIGINT, 
    one_month_price_change BIGINT, 
    one_year_price_change BIGINT, 
    db_created_at DATETIME DEFAULT now() NOT NULL, 
    db_updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id)
)

