
CREATE TABLE bronze_gamma_series (
    series_id VARCHAR(255) NOT NULL, 
    series_slug VARCHAR(255) NOT NULL, 
    ticker VARCHAR(255) NOT NULL, 
    title VARCHAR(255) NOT NULL, 
    series_type VARCHAR(255), 
    recurrence VARCHAR(255), 
    description TEXT, 
    subtitle VARCHAR(255), 
    image VARCHAR(500), 
    icon VARCHAR(500), 
    active BOOL, 
    closed BOOL, 
    archived BOOL, 
    is_new BOOL, 
    featured BOOL, 
    restricted BOOL, 
    comments_enabled BOOL, 
    competitive FLOAT, 
    start_date VARCHAR(255), 
    created_by VARCHAR(255), 
    updated_by VARCHAR(255), 
    created_at VARCHAR(255), 
    updated_at VARCHAR(255), 
    published_at VARCHAR(255), 
    volume_24_hr BIGINT, 
    liquidity FLOAT, 
    volume FLOAT, 
    comment_count INTEGER NOT NULL, 
    requires_translation BOOL NOT NULL, 
    db_created_at DATETIME NOT NULL DEFAULT now(), 
    db_updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY (series_id)
)

