
CREATE TABLE bronze_gamma_events (
    event_id VARCHAR(255) NOT NULL, 
    event_slug VARCHAR(255) NOT NULL, 
    ticker VARCHAR(255) NOT NULL, 
    title VARCHAR(255) NOT NULL, 
    description TEXT, 
    resolution_source VARCHAR(255), 
    start_date VARCHAR(255), 
    creation_date VARCHAR(255), 
    end_date VARCHAR(255), 
    image VARCHAR(500), 
    icon VARCHAR(500), 
    active BOOL NOT NULL, 
    closed BOOL NOT NULL, 
    archived BOOL NOT NULL, 
    is_new BOOL, 
    featured BOOL, 
    restricted BOOL, 
    liquidity FLOAT, 
    volume FLOAT, 
    open_interest BIGINT, 
    created_at VARCHAR(255), 
    updated_at VARCHAR(255), 
    competitive FLOAT, 
    volume_24_hr FLOAT, 
    volume_1_wk FLOAT, 
    volume_1_mo FLOAT, 
    volume_1_yr FLOAT, 
    enable_order_book BOOL, 
    liquidity_clob FLOAT, 
    neg_risk BOOL, 
    comment_count BIGINT, 
    cyom BOOL, 
    show_all_outcomes BOOL, 
    show_market_images BOOL, 
    enable_neg_risk BOOL, 
    automatically_active BOOL, 
    gmp_chart_mode VARCHAR(255), 
    neg_risk_augmented BOOL, 
    cumulative_markets BOOL, 
    pending_deployment BOOL, 
    deploying BOOL, 
    requires_translation BOOL, 
    neg_risk_market_id VARCHAR(255), 
    series_slug VARCHAR(255), 
    estimate_value BOOL, 
    sort_by VARCHAR(255), 
    deploying_timestamp VARCHAR(255), 
    event_date VARCHAR(255), 
    start_time VARCHAR(255), 
    color VARCHAR(255), 
    created_by VARCHAR(255), 
    country_name VARCHAR(255), 
    election_type VARCHAR(255), 
    featured_order BIGINT, 
    event_week BIGINT, 
    score VARCHAR(255), 
    elapsed VARCHAR(255), 
    period VARCHAR(255), 
    live BOOL, 
    ended BOOL, 
    game_id BIGINT, 
    finished_timestamp VARCHAR(255), 
    cant_estimate BOOL, 
    parent_event_id BIGINT, 
    estimated_value VARCHAR(255), 
    tweet_count BIGINT, 
    liquidity_amm BIGINT, 
    db_created_at DATETIME NOT NULL DEFAULT now(), 
    db_updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY (event_id)
)

