
CREATE TABLE bronze_gamma_markets (
    market_id VARCHAR(255) NOT NULL, 
    market_slug VARCHAR(255) NOT NULL, 
    event_id VARCHAR(255) NOT NULL, 
    event_slug VARCHAR(255) NOT NULL, 
    question VARCHAR(255) NOT NULL, 
    condition_id CHAR(66) NOT NULL, 
    resolution_source VARCHAR(255), 
    end_date VARCHAR(255), 
    liquidity VARCHAR(255), 
    start_date VARCHAR(255), 
    image VARCHAR(500), 
    icon VARCHAR(500), 
    description TEXT, 
    outcomes VARCHAR(255), 
    outcome_prices VARCHAR(255), 
    active BOOLEAN, 
    closed BOOLEAN, 
    closed_time VARCHAR(255), 
    market_maker_address VARCHAR(255), 
    created_at VARCHAR(255), 
    updated_at VARCHAR(255), 
    is_new BOOLEAN, 
    featured BOOLEAN, 
    submitted_by VARCHAR(255), 
    archived BOOLEAN, 
    resolved_by VARCHAR(255), 
    restricted BOOLEAN, 
    group_item_title VARCHAR(255), 
    question_id VARCHAR(255), 
    enable_order_book BOOLEAN, 
    order_price_min_tick_size FLOAT, 
    order_min_size BIGINT, 
    liquidity_num FLOAT, 
    end_date_iso VARCHAR(255), 
    start_date_iso VARCHAR(255), 
    has_reviewed_dates BOOLEAN, 
    game_start_time VARCHAR(255), 
    seconds_delay BIGINT, 
    clob_token_ids VARCHAR(255), 
    uma_bond VARCHAR(255), 
    uma_reward VARCHAR(255), 
    liquidity_clob FLOAT, 
    custom_liveness BIGINT, 
    accepting_orders BOOLEAN, 
    neg_risk BOOLEAN, 
    neg_risk_request_id VARCHAR(255), 
    ready BOOLEAN, 
    funded BOOLEAN, 
    accepting_orders_timestamp VARCHAR(255), 
    cyom BOOLEAN, 
    competitive FLOAT, 
    pager_duty_notification_enabled BOOLEAN, 
    approved BOOLEAN, 
    rewards_min_size BIGINT, 
    rewards_max_spread FLOAT, 
    spread FLOAT, 
    best_bid FLOAT, 
    best_ask FLOAT, 
    automatically_active BOOLEAN, 
    automatically_resolved BOOLEAN, 
    clear_book_on_start BOOLEAN, 
    manual_activation BOOLEAN, 
    neg_risk_other BOOLEAN, 
    game_id VARCHAR(255), 
    sports_market_type VARCHAR(255), 
    uma_resolution_status VARCHAR(255), 
    uma_resolution_statuses VARCHAR(255), 
    uma_end_date VARCHAR(255), 
    pending_deployment BOOLEAN, 
    deploying BOOLEAN, 
    deploying_timestamp VARCHAR(255), 
    rfq_enabled BOOLEAN, 
    event_start_time VARCHAR(255), 
    holding_rewards_enabled BOOLEAN, 
    fees_enabled BOOLEAN, 
    requires_translation BOOLEAN, 
    fee_type VARCHAR(255), 
    line FLOAT, 
    group_item_threshold VARCHAR(255), 
    group_item_range VARCHAR(255), 
    maker_base_fee BIGINT, 
    taker_base_fee BIGINT, 
    show_gmp_series BOOLEAN, 
    show_gmp_outcome BOOLEAN, 
    maker_rebates_fee_share_bps BIGINT, 
    volume VARCHAR(255), 
    volume_num FLOAT, 
    volume_clob FLOAT, 
    last_trade_price FLOAT, 
    volume_24_hr BIGINT, 
    volume_1_wk BIGINT, 
    volume_1_mo BIGINT, 
    volume_1_yr BIGINT, 
    volume_24_hr_amm BIGINT, 
    volume_1_wk_amm BIGINT, 
    volume_1_mo_amm BIGINT, 
    volume_1_yr_amm BIGINT, 
    volume_24_hr_clob BIGINT, 
    volume_1_wk_clob BIGINT, 
    volume_1_mo_clob BIGINT, 
    volume_1_yr_clob BIGINT, 
    volume_amm BIGINT, 
    liquidity_amm BIGINT, 
    one_day_price_change BIGINT, 
    one_hour_price_change BIGINT, 
    one_week_price_change BIGINT, 
    one_month_price_change BIGINT, 
    one_year_price_change BIGINT, 
    neg_risk_market_id VARCHAR(255), 
    series_color VARCHAR(255), 
    db_created_at DATETIME DEFAULT now() NOT NULL, 
    db_updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (market_id)
)

