
CREATE TABLE bronze_gamma_events (
    event_id VARCHAR(255) NOT NULL, 
    event_slug VARCHAR(255) NOT NULL, 
    ticker VARCHAR(255) NOT NULL, 
    title VARCHAR(255) NOT NULL, 
    description TEXT, 
    resolution_source VARCHAR(255), 
    start_date VARCHAR(255), 
    creation_date VARCHAR(255), 
    end_date VARCHAR(255), 
    image VARCHAR(500), 
    icon VARCHAR(500), 
    active BOOLEAN, 
    closed BOOLEAN, 
    archived BOOLEAN, 
    is_new BOOLEAN, 
    featured BOOLEAN, 
    restricted BOOLEAN, 
    liquidity FLOAT, 
    volume FLOAT, 
    open_interest BIGINT, 
    created_at VARCHAR(255), 
    updated_at VARCHAR(255), 
    competitive FLOAT, 
    volume_24_hr FLOAT, 
    volume_1_wk FLOAT, 
    volume_1_mo FLOAT, 
    volume_1_yr FLOAT, 
    enable_order_book BOOLEAN, 
    liquidity_clob FLOAT, 
    neg_risk BOOLEAN, 
    comment_count BIGINT, 
    cyom BOOLEAN, 
    show_all_outcomes BOOLEAN, 
    show_market_images BOOLEAN, 
    enable_neg_risk BOOLEAN, 
    automatically_active BOOLEAN, 
    gmp_chart_mode VARCHAR(255), 
    neg_risk_augmented BOOLEAN, 
    cumulative_markets BOOLEAN, 
    pending_deployment BOOLEAN, 
    deploying BOOLEAN, 
    requires_translation BOOLEAN, 
    neg_risk_market_id VARCHAR(255), 
    series_slug VARCHAR(255), 
    estimate_value BOOLEAN, 
    sort_by VARCHAR(255), 
    deploying_timestamp VARCHAR(255), 
    event_date VARCHAR(255), 
    start_time VARCHAR(255), 
    color VARCHAR(255), 
    created_by VARCHAR(255), 
    country_name VARCHAR(255), 
    election_type VARCHAR(255), 
    featured_order BIGINT, 
    event_week BIGINT, 
    score VARCHAR(255), 
    elapsed VARCHAR(255), 
    period VARCHAR(255), 
    live BOOLEAN, 
    ended BOOLEAN, 
    game_id BIGINT, 
    finished_timestamp VARCHAR(255), 
    cant_estimate BOOLEAN, 
    parent_event_id BIGINT, 
    estimated_value VARCHAR(255), 
    tweet_count BIGINT, 
    liquidity_amm BIGINT, 
    db_created_at DATETIME DEFAULT now() NOT NULL, 
    db_updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (event_id)
)

